// import {trenDest} from "../model/tren-dest";

// export const trenD : trenDest[]=[
//     new trenDest("Bournemouth","United Kingdom","./assets/trending-dest-img/bournemouth-uk.jpg","https://www.bournemouth.co.uk/things-to-do"),
//     new trenDest("Casablanca","Morocco","./assets/trending-dest-img/casablanca-morocco.jpg","https://www.google.co.in/destination/map/topsights?q=what+to+do+in+Casablanca+Morocco&site=search&output=search&dest_mid=/m/022b_&sa=X&ved=0ahUKEwjk0p2giPvZAhVEP48KHVwACyIQ6tEBCC4oBTAA"),
//     new trenDest("Gangneung","Korea","./assets/trending-dest-img/gangneung-korea.jpg","https://www.pyeongchang2018.com/en/gangneung"),
//     new trenDest("Gdansk","Poland","./assets/trending-dest-img/Gdansk-poland.jpg","https://wonderfulwanderings.com/things-to-do-in-gdansk/"),
//     new trenDest("Ishigaki","Japan","./assets/trending-dest-img/ishigaki-japan.jpg","http://trip-n-travel.com/listicle/10186/"),
//     new trenDest("Kapaa","Hawaii","./assets/trending-dest-img/Kapaa-Hawaii.jpg","https://www.google.co.in/destination/map/topsights?q=things+to+do+in+Kapaa+Hawaii&site=search&output=search&dest_mid=/m/0s08d&sa=X&ved=0ahUKEwjI4fj6ifvZAhWJ6Y8KHRLGANsQ6tEBCC0oBDAA"),
//     new trenDest("Mykonos","Greece","./assets/trending-dest-img/mykonos-greece.jpg","https://travel.usnews.com/Mykonos_Greece/Things_To_Do/"),
//     new trenDest("Nairobi","Kenya","./assets/trending-dest-img/Nairobi-kenya.jpg","https://www.africanbudgetsafaris.com/blog/ten-things-to-do-in-nairobi-pre-or-post-safari/"),
//     new trenDest("Nerja","Spain","./assets/trending-dest-img/nerja-spain.jpg","https://www.spain-holiday.com/Nerja/articles/best-things-to-do-in-nerja-costa-del-sol"),
//     new trenDest("Riga","Latvia","./assets/trending-dest-img/Riga-Latvia.jpg","https://adventurousmiriam.com/15-amazing-things-you-must-do-in-riga/"),
//     new trenDest("Rovinj","Croatia","./assets/trending-dest-img/rovinj-croatia.jpg","https://www.thecrazytourist.com/15-best-things-rovinj-croatia/"),
//     new trenDest("San Jose","Costa Rica","./assets/trending-dest-img/San-jose-Costa-rica.jpg","https://theculturetrip.com/central-america/costa-rica/articles/the-top-10-things-to-see-do-in-san-jose/"),

// ]
import { trenDest } from "../model/tren-dest";

export const trenD: trenDest[] = [
    new trenDest("Bournemouth", "United Kingdom", "./assets/trending-dest-img/bournemouth-uk.jpg","Nestled in a sheltered bay on the South Coast of England in the picturesque county of Dorset, Bournemouth has seven miles of sandy beaches for you to enjoy.There’s plenty to do in the resort or you can use the town as a base – stay and eat here while exploring the rest of Dorset’s history, heritage and picture - postcard scenery.Here are some of the best things to do in Bournemouth…Attractions: We’ve got plenty of places for you to visit, whatever the weather.There are museums, galleries, amusement arcades, crazy golf, play parks and an oceanarium.You can bring friends and family of all ages too – there’ll be something for everyone to enjoy.Activities:Are you an adrenaline junkie ? Or do you prefer a more relaxed pace ? You can hike on the clifftops or freewheel gently along the prom"),
    new trenDest("Casablanca", "Morocco", "./assets/trending-dest-img/casablanca-morocco.jpg", "Casablanca is a port city and commercial hub in western Morocco, fronting the Atlantic Ocean. The city's French colonial legacy is seen in its downtown Mauresque architecture, a blend of Moorish style and European art deco. Standing partly over the water, the enormous Hassan II Mosque, completed in 1993, has a 210m minaret topped with lasers directed toward Mecca. Elsewhere, the seaside Ain Diab district is favored for leisure and nightlife activities. Its Corniche area is a beachfront promenade with cafes, bars, hotels and restaurants. Located in the residential Oasis quarter, the Moroccan Jewish Museum explores the history of the country’s Jewish community. Downtown is the small Old Medina lined with shops. Running south of the city toward Oualidia and Essaouira, the beach-lined coast is a major summer holiday destination. Casablanca is also famous for the 1942 Humphrey Bogart film of the same name, with re-created Rick's Cafe a popular site."),
    new trenDest("Gangneung", "Korea", "./assets/trending-dest-img/gangneung-korea.jpg", "It is the number one tourist destination city of Korea. Let us introduce to you Gangneung, a city full of the cool scent of the sea and the pine trees.Gangneung is considered special in that it has access to both a lake and the sea. Gyeongpodae is a pavilion overlooking a Gyeongpo lake. It is said that one can see the moon five times when at Gyeongpodae. One sees the moon once in the sky, once reflected in the lake, once reflected in the sea, once reflected in the drinking glass, and once more in the eyes of a lover. The site of Gyeongpodae is known for its location east of the centre of the city. Inside the Gyeongpodae pavilion, built with 28 pillars, is the Gyeongpodaebu, a poem by Yul Gok. Gyeongpodaebu describes the movement of the heavens and the moon. The best view of the moon is on the 15th of the lunar month. The nearby Gyeongpo Beach has a sandy beach and a line of fresh seafood restaurants, with its proximity to Seoul making it a popular summer destination."),
    new trenDest("Gdansk", "Poland", "./assets/trending-dest-img/Gdansk-poland.jpg", "Gdańsk (Danzig in German) is a port city on the Baltic coast of Poland. At the center of its Main Town, reconstructed after WWII, are the colorful facades of Long Market, now home to shops and restaurants. Nearby is Neptune Fountain, a 17th-century symbol of the city topped by a bronze statue of the sea god. Gdańsk is also a center for the world’s amber trade; boutiques throughout the city sell the ossified resin."),
    new trenDest("Ishigaki", "Japan", "./assets/trending-dest-img/ishigaki-japan.jpg", "Venture into the great outdoors and spend days on end discovering all that Ishigaki Island has to offer. As the main island of the Yaeyama Islands, Ishigaki is one of Okinawa Prefecture’s most visited location for beach lovers. Go swimming in Japan’s refreshing south western waters, explore the underwater world of Ishigaki or soak up the island’s culture and history. What ever you decide to do, a great vacation is sure to ensue. "),
    new trenDest("Kapaa", "Hawaii", "./assets/trending-dest-img/Kapaa-Hawaii.jpg", "Kapaa, also spelled Kapa'a, means 'solid' in Hawaiian. Travelers find this small town, nestled at the base of Nounou (the Sleeping Giant) Mountain on Kauai tourist friendly with its diverse array of hotels, shopping centers, and restaurants. The Kinipopo Shopping Village is a favorite for its fun eateries and small keepsake shops. Look for the 'Kauai Made' logo for products made by local craftsmen using traditional materials. Kappa also offers water sports, including water skiing and kayaking."),
    new trenDest("Mykonos", "Greece", "./assets/trending-dest-img/mykonos-greece.jpg", "The main Mykonos attractions are the beaches, where you can sunbathe, relax, snorkel — even party. Paradise Beach is considered the no-brainer shore option here, though you should expect to be one of many tourists enjoying its soft sands. Away from the beach, tour Panagia Paraportiani in Chora, photograph the Windmills, or visit the island of Delos for its archaeological finds. Travelers also love Little Venice for its restaurants, shopping and postcard views. Save some energy for an evening out, as the island has long had a reputation for seaside hedonism."),
    new trenDest("Nairobi", "Kenya", "./assets/trending-dest-img/Nairobi-kenya.jpg", "Nairobi is Kenya’s capital city. In addition to its urban core, the city has Nairobi National Park, a large game reserve known for breeding endangered black rhinos and home to giraffes, zebras and lions. Next to it is a well-regarded elephant orphanage operated by the David Sheldrick Wildlife Trust. Nairobi is also often used as a jumping-off point for safari trips elsewhere in Kenya. In the city center, towers like the cylindrical KICC, home to the convention center, rise near attractions like the Nairobi National Museum, devoted to Kenyan art, artifacts, wildlife and early hominids. In upscale suburban Langata, the Giraffe Centre sanctuary features a hand-feeding platform. The Karen Blixen Museum, in the 'Out of Africa' author’s preserved colonial home, stands on the former farm that’s now an affluent suburb called Karen. The Bomas of Kenya cultural center, with huts representing Kenya's major ethnic groups, offers a look at traditional tribal life. Tribal arts and crafts are sold at the roving Maasai Market."),
    new trenDest("Nerja", "Spain", "./assets/trending-dest-img/nerja-spain.jpg", "Geographically speaking, you could not hope for a better location. Nerja sits at the mouth of the Chillar River and is wedged in between the Mediterranean Sea and the mountains of the Sierras de Tejeda.The name 'Nerja' is derived from the word 'narixa', an Arabic term which translates to 'bountiful spring.' The abundance of water in this area gives Nerja a tropical feel, a lushness that contributed to its significance in the sugar cane industry in the early 20th century. "),
    new trenDest("Riga", "Latvia", "./assets/trending-dest-img/Riga-Latvia.jpg", "Riga, Latvia’s capital, is set on the Baltic Sea at the mouth of the River Daugava. It's considered a cultural center and is home to many museums and concert halls. The city is also known for its wooden buildings, art nouveau architecture and medieval Old Town. The pedestrian-only Old Town has many shops and restaurants and is home to busy Livu Square, with bars and nightclubs."),
    new trenDest("Rovinj", "Croatia", "./assets/trending-dest-img/rovinj-croatia.jpg", "Rovinj is a stunning little city in Croatia filling every inch of a peninsula bordered on three sides by the Adriatic Sea. The core of the old town is mostly Venetian and built with pale limestone that glows in the sun, containing exciting fragments from every stage of its turbulent history.On a visit you can tour the maze of streets before a meal beneath a parasol at the picturesque working port. Beyond Rovinj you can seek out ancient ruins, visit unfrequented beaches and breathtaking natural spaces like the 10 kilometre-long Lim Fjord."),
    new trenDest("San Jose", "Costa Rica", "./assets/trending-dest-img/San-jose-Costa-rica.jpg", "San Jose is a large city surrounded by rolling hills in Silicon Valley, a major technology hub in California's Bay Area. Architectural landmarks, from the 1883 Italianate-style Oddfellows building to Spanish Colonial Revival structures, make up the downtown historic district. The downtown area is also home to the Tech Museum of Innovation, devoted to the exploration of science and technology.Staircases lead to nowhere at the legendary Winchester Mystery House, a sprawling Victorian mansion known for its elaborate maze of secret passageways. Artifacts dating from Egypt's Predynastic period through its early Islamic era are on display at the Rosicrucian Egyptian Museum, while the San Jose Museum of Art showcases contemporary works with an emphasis on West Coast art. Thousands of vendors gather several days a week at the San Jose Flea Market, outfitted with a carousel and mini Ferris wheel. At the Municipal Rose Garden, colorful blooms grow on an expanse of green space."),
]
